version: '3.9'
services:
  db:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cena
    ports:
      - 3306:3306
    networks:
      - redInterna
    container_name: db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - redInterna
    container_name: backend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/dist/:/var/www/html
    configs:
      - source: ./frontend/apache2.conf
        target: /etc/apache2/apache2.conf
      - source: ./frontend/000-default.conf
        target: /etc/apache2/sites-available/000-default.conf
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - redInterna
    container_name: frontend
networks:
  redInterna:
volumes:
  data:
