version: '3.9'
services:
  db:
    image: mysql:latest
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cena
    ports:
      - 3306:3306
    networks:
      - redInterna
    container_name: db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - redInterna
    container_name: backend
  frontend:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - redInterna
    container_name: frontend
networks:
  redInterna:
volumes:
  data:
